default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: car-listings_development

test:
  <<: *default
  database: car-listings_test

production:
  <<: *default
  database: car-listings_production
  username: car-listings
  password: <%= ENV['CAR-LISTINGS_DATABASE_PASSWORD'] %>
